version: '3.7'

services:
  every-io-test:
    container_name: every-io-test
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: sh -c "yarn install && yarn migration:run && yarn seed && yarn start"
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:13
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata: